<?php

namespace Qd\UnjourBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooksRepository extends EntityRepository
{


    public function  myFindByBooks()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('b')
            ->from($this->_entityName, 'b')
            ->groupBy('b.actors');
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
