<?php

namespace Qd\UnjourBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FrontNewspapersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontNewspapersRepository extends EntityRepository
{
    /*
     * TODO
     *
     * Afficher le Frontnewspaper
     *      - par date
     *      - par tag
     *      - par Newspaper
     *
     * Intégrer un Calendar (SymfonyCal ?)
     *      http://www.symfocal.com/
     */



    public function myFindByDate($madate)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('f')
            ->from($this->_entityName, 'f')
            ->where('f.dcreat = :madate')
            ->setParameter('madate', $madate);

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
