<?php

namespace Qd\UnjourBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotosRepository extends EntityRepository
{
    /*
     * TODO
     *
     * prévoir (éventuellement) la mise en place d'une page photo avec, à l'intérieur celle de l'Opendata
     */

    public function myFindByTags($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->join('p.tags', 't')
            ->addSelect('t')
            ->where('t.id = :id')
            ->setParameter("id", $id);

        $query = $qb->getQuery();
        return $query->getResult();
    }
}
