<?php

namespace Qd\UnjourBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicitesRepository extends EntityRepository
{
    /*
     * TODO
     *
     * afficher la Photo de la publicité en side :
     *      - par date
     *      - par tag
     */


    // Tous les Actors
    public function myFindByAll()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p')
            ->orderBy('p.dcreat', 'ASC');
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
