<?php

namespace Qd\UnjourBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorsRepository extends EntityRepository
{
    /*
     * TODO
     *
     * Obtenir :
     *  - nb de visites (clics) par jour
     *  - nb de visites unique par jour
     *  - nb de visites sur les 7 derniers jours
     *  - nb de visites sur les 30 derniers jours
     *  - nb de visites totales
     *  - liste des ip :
     *      - par nb de clic
     *      - par date
     */
}
